name: portfolio_app
description: A modern Flutter portfolio application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  device_frame: ^1.2.0
  flutter_animate: ^4.5.2
  rive: ^0.13.4
  provider: ^6.1.2
  url_launcher: ^6.2.6
  auto_size_text: ^3.0.0
  animated_button: ^0.2.0
  lottie: ^3.3.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/rive/
    - assets/