name: portfolio_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  glassmorphism: ^3.0.0 # Or you can use the manual glass card we build

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # To add assets, uncomment the lines below
  # assets:
  #   - assets/images/connect_icon.png